server:
  port: 9003
  shutdown: graceful
  netty:
    connection-timeout: 2s


spring:
  
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: sa
    password:
    url: r2dbc:h2:mem:///msorders
  h2:
    console:
      enabled: true  
    
    
  
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/ 
     
      
 
 
 
 
