server:
  port: 9003
  shutdown: graceful
  netty:
    connection-timeout: 2s


spring:
  
  
  r2dbc:
    username: sa
    password:
    url: r2dbc:h2:mem:///msorders
  h2:
    console:
      enabled: true
      path: /h2-console
    # Optional h2 console port if not set or set 0, available port is given
      port: 9003
    
    
  
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/ 
     
      
 
 
 
 
