server:
  port: 9003
  shutdown: graceful
  netty:
    connection-timeout: 2s


spring:
  
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: sa
    password:
    url: r2dbc:h2:mem:orders
    
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/ 
     
      
 
 
 
 
